export { FloatingButtonWhatsApp } from "./button-whats/floating-button-whatsapp.component";
export { CardList } from "./card-list/card-list.component";
export { Card } from "./card/card.component";
export { BtnSlider } from "./button-slider/button-slider.component";
export { Slider } from "./slider/slider.component";
export { Button } from "./button/button.component";
export { Footer } from "./footer/footer.component";
export { Header } from "./header/header.component";
export { Container } from "./container/conteiner.component";
